### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ilariamast** [hyyan/woo-poly-integration#429]
#### Can you reproduce this issue on default Wordpress theme (eg Storefront)?
yes

#### What product versions and settings are you using when this issue occurs?
* PHP: 7.3.1
* WordPress: 5.2.1
* WooCommerce: 3.6.4
* Polylang: [state if using Polylang PRO] basic version, 2.5.4
* Hyyan WooCommerce Polylang Integration: 1.3.0
* Browser: chrome

#### Steps to Reproduce
1. Two languages set
1. import a simple product and another one with variation
1. Duplicate a product in order to have the corrispondent translation

#### What I Expected
A product correctly duplicated

#### What Happened Instead
I get 2Warning: array_shift() expects parameter 1 to be array, object given in /home/ilariam6/public_html/fisto/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Utilities.php on line 271

Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /home/ilariam6/public_html/fisto/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Utilities.php:276 Stack trace: #0 /home/ilariam6/public_html/fisto/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Product/Variable.php(237): Hyyan\WPI\Utilities::getDefaultAttributesTranslation('876', 'en') #1 /home/ilariam6/public_html/fisto/wp-includes/class-wp-hook.php(286): Hyyan\WPI\Product\Variable->syncDefaultAttributes(928, Object(WP_Post), false) #2 /home/ilariam6/public_html/fisto/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /home/ilariam6/public_html/fisto/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /home/ilariam6/public_html/fisto/wp-includes/post.php(3940): do_action('save_post_produ...', 928, Object(WP_Post), false) #5 /home/ilariam6/public_html/fisto/wp-admin/includes/post.php(666): wp_insert_post(Array) #6 /home/ilariam6/public_html/fisto/wp-admin/post-new.php(66): get_default_post_to_edit('produ in /home/ilariam6/public_html/fisto/wp-content/plugins/woo-poly-integration/src/Hyyan/WPI/Utilities.php on line 276"

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

WordPress address (URL): http://fisto.ilariamast.com
Site address (URL): http://fisto.ilariamast.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wpcq_
MaxMind GeoIP Database: ✔
Dimensione totale database: 10.96MB
Dimensione dati database: 9.30MB
Dimensione indice database: 1.66MB
wpcq_woocommerce_sessions: Dati: 0.02MB + Indice: 0.02MB
wpcq_woocommerce_api_keys: Dati: 0.02MB + Indice: 0.03MB
wpcq_woocommerce_attribute_taxonomies: Dati: 0.02MB + Indice: 0.02MB
wpcq_woocommerce_downloadable_product_permissions: Dati: 0.02MB + Indice: 0.05MB
wpcq_woocommerce_order_items: Dati: 0.02MB + Indice: 0.02MB
wpcq_woocommerce_order_itemmeta: Dati: 0.02MB + Indice: 0.03MB
wpcq_woocommerce_tax_rates: Dati: 0.02MB + Indice: 0.06MB
wpcq_woocommerce_tax_rate_locations: Dati: 0.02MB + Indice: 0.03MB
wpcq_woocommerce_shipping_zones: Dati: 0.02MB + Indice: 0.00MB
wpcq_woocommerce_shipping_zone_locations: Dati: 0.02MB + Indice: 0.03MB
wpcq_woocommerce_shipping_zone_methods: Dati: 0.02MB + Indice: 0.00MB
wpcq_woocommerce_payment_tokens: Dati: 0.02MB + Indice: 0.02MB
wpcq_woocommerce_payment_tokenmeta: Dati: 0.02MB + Indice: 0.03MB
wpcq_woocommerce_log: Dati: 0.02MB + Indice: 0.02MB
wpcq_commentmeta: Dati: 0.02MB + Indice: 0.03MB
wpcq_comments: Dati: 0.02MB + Indice: 0.09MB
wpcq_duplicator_pro_entities: Dati: 0.02MB + Indice: 0.02MB
wpcq_duplicator_pro_packages: Dati: 0.02MB + Indice: 0.02MB
wpcq_links: Dati: 0.02MB + Indice: 0.02MB
wpcq_options: Dati: 1.11MB + Indice: 0.05MB
wpcq_pmxi_files: Dati: 0.02MB + Indice: 0.00MB
wpcq_pmxi_history: Dati: 0.02MB + Indice: 0.00MB
wpcq_pmxi_images: Dati: 0.02MB + Indice: 0.00MB
wpcq_pmxi_imports: Dati: 0.02MB + Indice: 0.00MB
wpcq_pmxi_posts: Dati: 0.02MB + Indice: 0.00MB
wpcq_pmxi_templates: Dati: 0.02MB + Indice: 0.00MB
wpcq_postmeta: Dati: 0.34MB + Indice: 0.14MB
wpcq_posts: Dati: 1.08MB + Indice: 0.06MB
wpcq_social_users: Dati: 0.02MB + Indice: 0.02MB
wpcq_termmeta: Dati: 0.02MB + Indice: 0.03MB
wpcq_terms: Dati: 0.02MB + Indice: 0.03MB
wpcq_term_relationships: Dati: 0.05MB + Indice: 0.02MB
wpcq_term_taxonomy: Dati: 0.02MB + Indice: 0.03MB
wpcq_usermeta: Dati: 0.02MB + Indice: 0.03MB
wpcq_users: Dati: 0.02MB + Indice: 0.05MB
wpcq_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
wpcq_wc_product_meta_lookup: Dati: 0.02MB + Indice: 0.09MB
wpcq_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
wpcq_wfblockediplog: Dati: 0.02MB + Indice: 0.00MB
wpcq_wfblocks7: Dati: 0.02MB + Indice: 0.05MB
wpcq_wfconfig: Dati: 0.42MB + Indice: 0.00MB
wpcq_wfcrawlers: Dati: 0.02MB + Indice: 0.00MB
wpcq_wffilechanges: Dati: 0.02MB + Indice: 0.00MB
wpcq_wffilemods: Dati: 3.52MB + Indice: 0.00MB
wpcq_wfhits: Dati: 0.02MB + Indice: 0.05MB
wpcq_wfhoover: Dati: 0.02MB + Indice: 0.02MB
wpcq_wfissues: Dati: 0.02MB + Indice: 0.06MB
wpcq_wfknownfilelist: Dati: 1.52MB + Indice: 0.00MB
wpcq_wflivetraffichuman: Dati: 0.02MB + Indice: 0.02MB
wpcq_wflocs: Dati: 0.02MB + Indice: 0.00MB
wpcq_wflogins: Dati: 0.05MB + Indice: 0.03MB
wpcq_wfls_2fa_secrets: Dati: 0.02MB + Indice: 0.02MB
wpcq_wfls_settings: Dati: 0.02MB + Indice: 0.00MB
wpcq_wfnotifications: Dati: 0.02MB + Indice: 0.00MB
wpcq_wfpendingissues: Dati: 0.02MB + Indice: 0.06MB
wpcq_wfreversecache: Dati: 0.02MB + Indice: 0.00MB
wpcq_wfsnipcache: Dati: 0.02MB + Indice: 0.05MB
wpcq_wfstatus: Dati: 0.13MB + Indice: 0.09MB
wpcq_wftrafficrates: Dati: 0.02MB + Indice: 0.00MB
wpcq_yith_wcwl: Dati: 0.02MB + Indice: 0.02MB
wpcq_yith_wcwl_lists: Dati: 0.02MB + Indice: 0.03MB
wpcq_yoast_seo_links: Dati: 0.02MB + Indice: 0.02MB
wpcq_yoast_seo_meta: Dati: 0.02MB + Indice: 0.00MB

### Post Type Counts ###

attachment: 73
blocks: 9
customize_changeset: 10
featured_item: 8
nav_menu_item: 20
page: 25
polylang_mo: 2
post: 9
product: 12
product_variation: 28
revision: 158
scheduled-action: 5
wpcf7_contact_form: 9

### Security ###

Secure connection (HTTPS): ❌
					Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (14) ###

Polylang: by Frédéric Demarle – 2.5.4
Classic Editor: by Contributori WordPress – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Duplicate Post: by Enrico Battocchi – 3.2.2
Product Variation Swatches for Woocommerce: by ThemeHigh – 1.0.2
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.3.0 – Non testato con la versione attiva di WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.14
WooCommerce Product Image Flipper: by jameskoster – 0.4.2 – Non testato con la versione attiva di WooCommerce
WooCommerce: by Automattic – 3.6.4
WooSidebars: by WooCommerce – 1.4.5
Wordfence Security: by Wordfence – 7.3.2
Yoast SEO: by Team Yoast – 11.3 – Non testato con la versione attiva di WooCommerce
WP Fastest Cache: by Emre Vona – 0.8.9.4
YITH WooCommerce Wishlist: by YITH – 2.2.10

### Inactive Plugins (1) ###

WooCommerce Blocks: by Automattic – 2.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #62 - /shop/
Carrello: #550 - /carrello/
Cassa: #60 - /checkout/
Il mio account: ❌ La pagina non è impostata
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.8.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### Action Scheduler ###

Complete: 4
Oldest: 2019-05-13 15:59:02 +0000
Newest: 2019-06-04 15:06:49 +0000

Pending: 1
Oldest: 2019-06-11 15:06:49 +0000
Newest: 2019-06-11 15:06:49 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by Jon007** [comment]
Hi, please try Hyyan WooCommerce Polylang Integration 1.4 preview see 
https://github.com/hyyan/woo-poly-integration/releases

**Comment by ilariamast** [comment]
Thank you Jon!
